source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'GitPopJava' do
    pod 'OctoKit'
    pod 'SDWebImage'
    target 'GitPopJavaTests' do
        inherit! :search_paths
    end
end